import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.

  int experiments = Integer.parseInt(args[0]);
  
  boolean boy= false;
  boolean girl= false;
  int count = 0;
  int sum = 0;
  int two = 0;
  int three = 0;
  int fourMore = 0;
  String details = "";
  
  for (int i = 0; i < experiments; i++){ //runs X experiments
      girl = false;
      boy = false;
      count = 0;
      details = "";
  while (! (girl && boy == true)){
    double kid = generator.nextDouble();
	count = count + 1;
	
	if (kid >= 0 && kid < 0.5){
	 details+= "b ";
	 boy = true;
	 }
	else if (kid >= 0.5) {
	 details+= "g ";
	 girl = true;
	 }
	 
   }
   sum+=count;
	
   if (count == 2) {
       two++;
   }
   if (count == 3) {
       three++;
   }
   if (count >= 4) { //count is 4 or more
       fourMore++; }
}
  double average = (double)sum/ experiments;
  System.out.println ("Average: " + average + " children to get at least one of each gender.");
  System.out.println ("Number of families with 2 children: " + two);
  System.out.println ("Number of families with 3 children: " + three);
  System.out.println ("Number of families with 4 or more children: " + fourMore);
  int max = Math.max (Math.max(two,three), fourMore);
  if (max == two){
  System.out.println ("The most common number of children is 2.");
}
  if (max == three){
    System.out.println ("The most common number of children is 3.");
}
  if (max == fourMore){
      System.out.println ("The most common number of children is 4 or more.");
  }
		    
	}
}
